apiVersion: apps/v1
kind: Deployment
metadata:
  name: haha5
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: haha5
  template:
    spec:
      containers:
        - name: haha5
          image: fake-image
          resources:
            requests:
              memory: 128Mi
              cpu: 0.1
            limits:
              memory: 512Mi
              cpu: 1.0
          ports:
            - containerPort: 80
              name: http
          envFrom:
          - configMapRef:
              name: haha5-config
          env:
          - name: SERVER_PORT
            value: "80"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
